modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="genji"
version="${mod_version}"
displayName="Genji Mod"
description="Adds Genji's abilities: shuriken, deflect, dash, and dragonblade."

[[dependencies.genji]]
modId="geckolib"
mandatory=true
versionRange="[4.7.0,5.0.0)"
ordering="NONE"
side="BOTH"
